# Generated by Django 2.1 on 2020-02-04 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0002_auto_20190307_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField(blank=True, default='', null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ошибка отправки уведомления',
                'verbose_name_plural': 'Ошибки отправки уведомления',
            },
        ),
        migrations.AddField(
            model_name='notify',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Отправителя'),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отключить аккаунт'),
        ),
        migrations.AlterField(
            model_name='smtpaccount',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль пользователя'),
        ),
        migrations.AlterField(
            model_name='smtpaccount',
            name='sender',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='smtpaccount',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='notifyerrorlog',
            name='notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='garpix_notify.Notify', verbose_name='Notify'),
        ),
    ]
