# Generated by Django 3.0.5 on 2020-04-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('garpix_notify', '0003_auto_20200204_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала отправки'),
        ),
        migrations.AddField(
            model_name='notifytemplate',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала отправки'),
        ),
        migrations.AddField(
            model_name='notifyuserlist',
            name='mail_to_all',
            field=models.BooleanField(default=False, verbose_name='Отправить всем'),
        ),
        migrations.AddField(
            model_name='notifyuserlist',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Группы пользователей'),
        ),
        migrations.AlterField(
            model_name='smtpaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включить аккаунт'),
        ),
    ]
