# Generated by Django 2.0.7 on 2019-03-07 12:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_for_admin', models.CharField(blank=True, default='', max_length=100, verbose_name='Название для админа')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('menu_type', models.CharField(choices=[('disabled', 'Not shown'), ('main_menu', 'Main menu')], default='', max_length=100, verbose_name='Тип меню')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Внешний URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('target_blank', models.BooleanField(default=False, verbose_name='Открывать в новом окне')),
                ('css_class', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительный класс CSS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('sort', models.IntegerField(default=100, help_text='Чем меньше число, тем выше будет элемент в списке.', verbose_name='Сортировка')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('page', models.ForeignKey(blank=True, help_text='Если этот пункт не выбран, то будет использовано следующее поле "Внешний URL"', null=True, on_delete=django.db.models.deletion.CASCADE, to='garpix_page.Page', verbose_name='Страница, на которую ведет пункт меню')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='garpix_menu.MenuItem', verbose_name='Родительский пункт меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ('sort',),
            },
        ),
    ]
