# Generated by Django 3.1.1 on 2021-02-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200926_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Telegram ID'),
        ),
    ]
