# Generated by Django 2.1 on 2020-02-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0002_page_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='login_required',
            field=models.BooleanField(default=False, verbose_name='Требовать авторизацию для просмотра?'),
        ),
    ]
