# Generated by Django 3.0.5 on 2020-04-27 13:44

from django.db import migrations, models
import django.db.models.manager
import garpix_page.utils.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0003_auto_20200204_1319'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='seo_image',
            field=models.FileField(blank=True, null=True, upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='SEO изображение'),
        ),
        migrations.AlterField(
            model_name='page',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
