# Generated by Django 3.1.1 on 2020-09-26 09:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0004_auto_20200427_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='display_on_sitemap',
            field=models.BooleanField(default=True, verbose_name='Отображать в карте сайта'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True, default='', verbose_name='SEO описание (description)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SEO описание (description)'),
        ),
    ]
