# Generated by Django 3.0.5 on 2020-04-28 10:32

import django.core.validators
from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('garpix_page', '0004_auto_20200427_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать рекламу')),
                ('image',
                 models.FileField(blank=True, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path,
                                  validators=[django.core.validators.FileExtensionValidator(
                                      allowed_extensions=['jpeg', 'jpg', 'png', 'mp4'])], verbose_name='Изображение')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка')),
                ('reclaim_type', models.IntegerField(
                    choices=[(1, 'Горизонтальный рекламный блок'), (2, 'Вертикальный рекламный блок'),
                             (3, 'Диагональный рекламный блок')], default=1, verbose_name='Тип рекламы')),
                ('max_show_count', models.PositiveIntegerField(default=0, verbose_name='Максимальное число показов')),
                ('show_count', models.PositiveIntegerField(default=0, verbose_name='Число показов')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
            },
        ),
        migrations.CreateModel(
            name='ReclaimSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='Показывать рекламу')),
                ('pages', models.ManyToManyField(blank=True, to='garpix_page.Page',
                                                 verbose_name='Страницы для отображения рекламы')),
            ],
            options={
                'verbose_name': 'Настройка показа рекламы',
            },
        ),
    ]